### ISSUE TITLE
Incorrect `bash-completion` directory path when `XDG_DATA_HOME` is present.

### ISSUE THREAD

**Issue by KaranAhlawat** [carapace-sh/carapace-bridge#194]
In the [bash.go](https://github.com/carapace-sh/carapace-bridge/blob/master/pkg/bridges/bash.go) file, when creating the list of locations to look for completions, if the user doesn't have `BASH_COMPLETION_USER_DIR` set, but does have `XDG_DATA_HOME` set, then the location it adds to the list ends up being `XDG_DATA_HOME/.local/share/bash-completion/completions`. However, in most cases, the value of `XDG_DATA_HOME` itself is set to `/home/user/.local/share`. So, the location ends up being, `/home/user/.local/share/.local/share/bash-completion/completions`, which is incorrect as the directory doesn't exist.

The fix is pretty small, and easy to implement. Please let me know if I should raise a PR for it.

**Comment by rsteube** [comment]
PR is welcome
