### ISSUE TITLE
bash bridge spams a script to bash history

### ISSUE THREAD

**Issue by name-snrl** [carapace-sh/carapace-bridge#197]
Any idea why this entire script, line by line, goes into the bash history when I try to complete a command using bash bridge in both `nushell` and `fish`?

https://github.com/carapace-sh/carapace-bridge/blob/a3a0a4692b57b22a52ee7f3ca0612ef72984f759/pkg/actions/bridge/bash.sh#L1-L25

Every time I try to get a complete for the arguments of `nix-store`, it causes the bash history to be filled with the contents of the script:

```bash
# ~/.bash_history
j n c
fish
git st
fish
bash
vi ~/.bash_history
ls
#!/bin/bash
COMP_WORDS=($COMP_LINE)
if [ "${COMP_LINE: -1}" = " " ]; then   COMP_WORDS+=(""); fi
COMP_CWORD=$((${#COMP_WORDS[@]} - 1))
COMP_POINT=${#COMP_LINE}
# bash-completions
[ -f /data/data/com.termux/files/usr/share/bash-completion/bash_completion ] && source /data/data/com.termux/files/usr/share/bash-completion/bash_completion # termux
[ -f /usr/local/share/bash-completion/bash_completion ] && source /usr/local/share/bash-completion/bash_completion # osx
[ -f /usr/share/bash-completion/bash_completion ] && source /usr/share/bash-completion/bash_completion # linux
__load_completion "${COMP_WORDS[0]}"
$"$(complete -p "${COMP_WORDS[0]}" | sed -r 's/.* -F ([^ ]+).*/\1/')"
for i in "${COMPREPLY[@]}"; do   if [[ -d "${i}" && "${i}" != */ ]]; then     echo "${i}/";   else     echo "${i}";   fi; done
#!/bin/bash
COMP_WORDS=($COMP_LINE)
if [ "${COMP_LINE: -1}" = " " ]; then   COMP_WORDS+=(""); fi
COMP_CWORD=$((${#COMP_WORDS[@]} - 1))
COMP_POINT=${#COMP_LINE}
# bash-completions
[ -f /data/data/com.termux/files/usr/share/bash-completion/bash_completion ] && source /data/data/com.termux/files/usr/share/bash-completion/bash_completion # termux
[ -f /usr/local/share/bash-completion/bash_completion ] && source /usr/local/share/bash-completion/bash_completion # osx
[ -f /usr/share/bash-completion/bash_completion ] && source /usr/share/bash-completion/bash_completion # linux
__load_completion "${COMP_WORDS[0]}"
$"$(complete -p "${COMP_WORDS[0]}" | sed -r 's/.* -F ([^ ]+).*/\1/')"
for i in "${COMPREPLY[@]}"; do   if [[ -d "${i}" && "${i}" != */ ]]; then     echo "${i}/";   else     echo "${i}";   fi; done
```

### workaround
```bash
#~/.config/carapace/bridge/bash/.bashrc
export HISTFILE=/dev/null
```

### carapace version
```bash
> carapace --version
1.0.2
```

### configuration
```bash
source <(/nix/store/3wrri355w1kdcd5rc0lg2jscq733hyy6-carapace-1.0.2/bin/carapace _carapace bash)

export CARAPACE_BRIDGES='fish,bash,zsh'
export CARAPACE_EXCLUDES='nix'
```

**Comment by name-snrl** [comment]
BTW, not all OS have /bin/bash, shouldn't we replace it with #!/usr/bin/env bash?
p.s. NixOS is one of such non-fhs OS, there is no /bin/bash. although bash bridge works

https://github.com/carapace-sh/carapace-bridge/blob/a3a0a4692b57b22a52ee7f3ca0612ef72984f759/pkg/actions/bridge/bash.sh#L1

**Comment by rsteube** [comment]
> Any idea why this entire script, line by line, goes into the bash history when I try to complete a command using bash bridge in both nushell and fish?

It is [passed  in interactive mode](https://github.com/carapace-sh/carapace-bridge/blob/master/pkg/actions/bridge/bash.go#L50) to bash. Seems this way it ends up in the history.

---

> ```sh 
> export HISTFILE=/dev/null
> ```

[Turning it off](https://unix.stackexchange.com/questions/10922/temporarily-suspend-bash-history-on-a-given-shell#10923) in the script should indeed fix it.
```sh
set +o history # temporarily turn off history
```

---

>
> ```sh
> #!/usr/bin/env bash?
> ```

Can do. I works either way in this case since it is passed directly to the bash command.

**Comment by name-snrl** [comment]
> [Turning it off](https://unix.stackexchange.com/questions/10922/temporarily-suspend-bash-history-on-a-given-shell#10923) in the script should indeed fix it.

I think a better solution would be to add `+O history` directly to the arguments when calling bash, instead of adding `set +o history` to the script, if I understand your suggestion correctly
